out := $(OUT_DIR)
src := $(out)/src

archive := lapack-3.5.0.tgz
url := http://www.netlib.org/lapack/$(archive)
lib := $(out)/libblas.a
archive := $(out)/$(archive)

$(lib): $(src)/librefblas.a
	cp $< $@

$(src)/librefblas.a: $(src)/make.inc
	$(MAKE) -C $(src) blaslib

$(src)/make.inc: $(archive)
	mkdir -p $(src)
	tar -xzf $(archive) --strip=1 -C $(src)
	cp $@.example $@

$(archive):
	curl $(url) -o $@
